# Generated by Django 5.2.12 on 2026-03-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('webapps', 'Web Applications'), ('maps', 'Maps')], max_length=20)),
                ('image', models.ImageField(upload_to='projects/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.URLField()),
                ('github_link', models.URLField()),
                ('pdf', models.FileField(upload_to='projects/')),
                ('technology', models.CharField()),
            ],
        ),
    ]
