# Generated by Django 5.2.12 on 2026-03-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='featured_image',
        ),
    ]
