# Generated by Django 5.2.12 on 2026-03-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_image_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(default='placeholder.jpg', upload_to='projects/'),
        ),
    ]
