# Generated by Django 5.2.12 on 2026-03-09 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_featured_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='featured_image',
            new_name='image',
        ),
    ]
