# Generated by Django 5.2.12 on 2026-03-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='about',
            name='github',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='linkedin',
            field=models.URLField(),
        ),
    ]
